# Generated by Django 5.2b1 on 2025-05-05 13:41

import blog.storage
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import django_currentuser.db.models.fields
import django_currentuser.middleware
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique id')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('_created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('_updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('_created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique id')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('_created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('_updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('_created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique id')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('_created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('_updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, storage=blog.storage.BlogImageStorage(), upload_to='post/')),
                ('_created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('_updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('category', models.ManyToManyField(blank=True, to='blog.category')),
                ('tag', models.ManyToManyField(blank=True, related_name='articles', to='blog.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['id'], name='category_id_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['id'], name='tag_id_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['id'], name='post_id_idx'),
        ),
    ]
